#!/bin/bash

CUDA_VISIBLE_DEVICES=0,1 python train.py \
    --num_workers 96 \
    --devices 2 \
    --num_nodes 1 \
    --accelerator gpu \
    --text_model_id bigcode/starcoderbase-1b \
    --structure_model_id jinaai/jina-embeddings-v2-base-en \
    --pad_token_id 0 \
    --dropout_p 0. \
    --default_root_dir ./ \
    --data_prefix ast_cfc \
    --train_datadir /home/sushko/LlavaCode/data/train \
    --valid_datadir /home/sushko/LlavaCode/data/valid \
    --log_dir ./logs/ \
    --seed 1234 \
    --lr 2e-3 \
    --lr_scheduler_type cosine \
    --weight_decay 0. \
    --gradient_clip_val 1.0 \
    --max_steps -1 \
    --max_epochs 10 \
    --warmup_steps 500 \
    --train_batch_size 16 \
    --valid_batch_size 16 \
    --accumulate_grad_batches 4 \
    --training_stage 1 \
    --log_every_n_steps 20 \
    --save_step_frequency 500 \
    --val_check_interval 100 \
    --precision 'bf16-mixed'
