STRUCTURE_TOKEN = '<CODE_STRUCTURE>'

FIMMAP = {
    'qwen2.5': ['<|fim_prefix|>', '<|fim_suffix|>', '<|fim_middle|>'],
    'starcoder': ['<fim_prefix>', '<fim_suffix>', '<fim_middle>'],
}

PARAPHRASE_CUES = [
    "# Code in the above block is functionally equivalent to the block below",
    "# The logic above is re-expressed in the block below",
    "# Equivalent implementation continues in the block below",
    "# These two code fragments achieve the same result; the second is shown below",
    "# Background: This represents the same logic implemented in the block below",
    "# Alternative syntax and structure are shown in the block below",
    "# In other words, the above corresponds exactly to the block below",
    "# Same functionality whether expressed above or in the block below",
    "# Unpacked and rewritten in the block below",
    "# Reformulated version is in the block below",
    "# Background: Same meaning expressed differently in the block below",
    "# Stripped down, the above is another representation of the block below",
    "# The essence of the above appears again in the block below",
    "# Background: Code in the above snippet is functionally equivalent to the snippet below",
    "# Background: The logic above is re-expressed in the code snippet below",
    "# Equivalent implementation continues in the snippet below",
    "# These two code snippets achieve the same result; the second is shown below",
    "# Background: This represents the same logic implemented in the code snippet below",
    "# Alternative syntax and structure are shown in the snippet below",
    "# In other words, the above corresponds exactly to the code snippet below",
    "# Same functionality whether expressed above or in the code snippet below",
    "# Unpacked and rewritten in the snippet below",
    "# Reformulated version is in the code snippet below",
    "# Background: Same meaning expressed differently in the snippet below",
    "# Stripped down, the above is another representation of the snippet below",
    "# The essence of the above appears again in the code snippet below",
    "# The code above is equivalent to the implementation below",
    "# The functionality above is re-implemented in the code below",
    "# Another way to write the above is shown in the code snippet below",
    "# This function is a restatement of the one above",
    "# Logic above is mirrored in the function below",
    "# Alternate form of the above code is presented below",
    "# Code above matches the fragment shown below",
    "# Equivalent algorithm appears in the snippet below",
    "# Alternative formulation is shown in the code below",
    "# The above approach is replicated in the code snippet below",
    "# Equivalent routine is provided in the function below",
    "# Implementation above is matched by the one below",
    "# Another representation of the above algorithm appears below",
]

# PARAPHRASE_CUES = [
#     "Background: [X] implements the same functionality as [D]",
#     "Background: [X] Can you re-express the above code in your own way? [D]",
#     "[X] Please provide a reinterpretation of the preceding code snippet. [D]",
#     "These two code fragments are equivalent in essence: (1) [X] (2) [D]",
#     "Background: [X] is a reimplementation of what? [D]",
#     "[X] Could you give me a different version of the code above? [D]",
#     "In other words, background: [X] is just another way of writing: [D]",
#     "You’re achieving the same result whether you write background: [X] or [D]",
#     "[X] After unpacking the ideas in the code above, we get: [D]",
#     "[X] Please offer a restatement of the code snippet I’ve just read. [D]",
#     "Background: [X], which is functionally equivalent to: [D]",
#     "Strip away the syntax, and you’ll find [X] is simply another rendition of: [D]",
#     "The essence of background: [X] is captured again in the following code: [D]",
# ]
